### ISSUE TITLE
After CRON expression selection, prompt text is missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#104]
CRON表达式选择后，缺少文本“预计未来5次检查时间”
![image](https://user-images.githubusercontent.com/95004531/210744231-51715f7c-b37a-4a5e-bb75-0cbfc0b4c964.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by wzh425** [comment]
![image](https://user-images.githubusercontent.com/13762077/211318667-4cf4dd67-fc84-41a9-8012-54d7f3184632.png)
