### ISSUE TITLE
After the CRON expression is selected, the style is not consistent with the UI

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#105]
CRON 表达式选择后，样式与UI不一致
实际结果：
![image](https://user-images.githubusercontent.com/95004531/210744823-e87e158b-8f17-44d2-b06d-93b76cdec38f.png)

预期结果：
![image](https://user-images.githubusercontent.com/95004531/210744962-2c97b399-7811-43b0-873f-03dd245dbf75.png)

**Comment by zyz** [comment]
#164 repair edit alert rule select cron style inconsistency
