### ISSUE TITLE
The alarm rule does not trigger the alarm

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#117]
告警规则设置5分钟触发一次，待处理状态下，超过5分钟未触发告警
![image](https://user-images.githubusercontent.com/95004531/210762563-ddb84a5e-a8ee-482f-ac98-68b6f2ca65e8.png)

**Comment by wzh425** [comment]
检查过发现查询表达式不对 应该时你中途修改过表达式
