### ISSUE TITLE
The description of the alarm rule, expression component adjustment

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#134]
告警规则表达式后的“？”，使用Menu组件，样式调整为Tooltips的样式，点击网址后，在新的标签页打开网址。
![企业微信截图_16732370372667](https://user-images.githubusercontent.com/95004531/211239384-af8785e3-5771-44c5-8366-809b063be798.png)

**Comment by wzh425** [comment]
建议tooltip组件支持更为合理

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by wzh425** [comment]
已用Menu组件实现
