### ISSUE TITLE
An error occurs when an alarm message template is selected

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#138]
处理告警选择消息模板报错

https://user-images.githubusercontent.com/95004531/211263870-69559068-1a09-4f02-b6e8-e3eb1d2a73ac.mp4

**Comment by wzh425** [comment]
BDialog组件AttachAsync方法出错 本地复现不了 blazor 近期对这块有改掉提了pr 等pr合进去再观察下

**Comment by LazyEar0** [comment]
1.0.0观察一下，如未再次出现，关闭此issue

**Comment by wzh425** [comment]
当前版本没有复现
