### ISSUE TITLE
The alarm rule cannot generate alarm history, and the Job fails to run

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#154]
告警规则无法生成告警历史，Job运行失败
![image](https://user-images.githubusercontent.com/95004531/212336370-bb686a86-5c49-4759-90cb-1899735c82f7.png)
![image](https://user-images.githubusercontent.com/95004531/212336471-57616f09-3fe7-48d2-88d7-e674673a469a.png)

**Comment by wzh425** [comment]
容器配置问题
