### ISSUE TITLE
The bottom of the alarm rule is truncated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#173]
告警规则底部被截断
![image](https://user-images.githubusercontent.com/95004531/222716342-b4d9117d-1d8e-4cc9-8f0b-d27b7dbd1321.png)

**Comment by LazyEar0** [comment]
日志/指标告警规则，监控设置 底部也被截断了
![image](https://user-images.githubusercontent.com/95004531/223938309-3b4c1fcb-1051-4cc8-b13e-37e6f9b6c422.png)

**Comment by wzh425** [comment]
等待pr合并
