### ISSUE TITLE
Hover over the indicator and add tooltips to display the full name of the selected indicator

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#201]
鼠标移至指标上，增加tooltips，显示已选中指标的全称
![image](https://user-images.githubusercontent.com/95004531/227884982-16031063-37eb-43f5-8fc8-bec98709a891.png)

**Comment by kogel-net** [comment]
#209

**Comment by kogel-net** [comment]
#209

**Comment by LazyEar0** [comment]
此问题仍存在
