### ISSUE TITLE
Permission information, bottom button is not aligned

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#212]
权限信息，底部按钮没对齐
![image](https://user-images.githubusercontent.com/95004531/228478636-6427bb1f-2b5d-4a3a-8659-7762c757d015.png)

**Comment by MayueCif** [comment]
![image](https://user-images.githubusercontent.com/6133287/229031204-2e82cb29-7135-44c7-b832-55a49a0133d1.png)

**Comment by MayueCif** [comment]
![image](https://user-images.githubusercontent.com/6133287/229031309-33e8c95e-c485-497f-8c32-a698628bee5b.png)
