### ISSUE TITLE
After an alarm rule is deleted, the name of the corresponding rule is missing in the alarm history

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#223]
告警规则被删除后，告警历史中，对应规则的名称缺失。告警规则被删除，应不会影响已生成的告警历史
![image](https://user-images.githubusercontent.com/95004531/229426014-3b957b9c-d7fb-4ffb-adb7-3cff79705d7d.png)

**Comment by kogel-net** [comment]
#230
