### ISSUE TITLE
View the alarm history, and the abscissa text overlaps

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#284]
查看告警历史，横坐标文本重叠
![企业微信截图_16819582592123](https://user-images.githubusercontent.com/95004531/233301517-ffc5c1f9-bc79-42a3-ae48-825815061d54.png)
![企业微信截图_16819582833301](https://user-images.githubusercontent.com/95004531/233301547-ff0f0371-bb99-4d38-a94f-6cc35c76e8eb.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by kogel-net** [comment]
https://github.com/masastack/MASA.Alert/pull/286
