### ISSUE TITLE
Alarm details open chart data missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#296]
告警详情打开图表数据缺失
![image](https://user-images.githubusercontent.com/95004531/234476415-36f49126-c29b-45f6-b7ca-097fb7dae0b6.png)
![image](https://user-images.githubusercontent.com/95004531/234476439-2abf8701-d8df-4a68-b8d7-02d4a26bde74.png)

**Comment by wzh425** [comment]
https://github.com/masastack/MASA.Alert/pull/310
