### ISSUE TITLE
In alarm details, different alarm information is displayed after different alarm nodes are switched

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#42]
告警详情，点击图表中告警的不同节点，下方应切换至该节点对应的告警详情
![image](https://user-images.githubusercontent.com/95004531/209765722-37004f2f-e083-4469-9b27-b3872bbfdc10.png)

**Comment by wzh425** [comment]
需要MECharts组件将init完的chart对象 开放给我使用   以便我监听点击事件

**Comment by doddgu** [comment]
@capdiem PTAL
