### ISSUE TITLE
After the alarm is cleared, the recovery notification is triggered

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#66]
1.添加告警规则，告警后发送通知，恢复通知；
2.触发告警规则，生成告警历史，为待处理状态；
3.进入告警历史详情，处理告警，直接选择“已处理”，处理完成发送通知开关关闭，不通知。
实际结果：
处理完成后，触发了恢复通知。
预期结果：
处理完成后，应不发送通知，处理完成是否发送通知，应根据处理完成时是否选择通知进行判断。
设置告警规则时的恢复通知，仅为自动恢复是否通知，此处为避免歧义，可将问题调整为“自动恢复发送通知”
![image](https://user-images.githubusercontent.com/95004531/209935637-c57a5352-f3d2-4973-9ee9-451eb74567ce.png)

**Comment by wzh425** [comment]
已处理才是处理完成 才会发送处理完成之后的通知  分配第三方不会
