### ISSUE TITLE
Data is lost when the alarm rule page is edited

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#67]
进入编辑告警规则页面，会出现数据丢失的情况
![image](https://user-images.githubusercontent.com/95004531/209938864-ccf56b7b-fdf9-45d0-a63a-5e12ef364906.png)

![image](https://user-images.githubusercontent.com/95004531/209938927-b4855141-5f51-4995-917d-a447c904c7b1.png)

**Comment by wzh425** [comment]
Masa.Stack.Components  190的bug 等待组件修复
