### ISSUE TITLE
Time selector component, icon spacing needs to be adjusted

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Alert#97]
时间选择器组件，icon间距需要调整
实际结果：
![image](https://user-images.githubusercontent.com/95004531/210724266-954a8e15-29a3-4e83-88c9-2e3c6d519eb4.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/210724335-f9772125-2e9c-475f-97aa-c2836a8c3b28.png)

**Comment by LazyEar0** [comment]
样式与UI沟通后，根据UI的效果图调整

**Comment by MapleWithoutWords** [comment]
@LazyEar0 你看的是没值的时候，可能它的间隔比较大，如果你选择了时间，间隔不大的。看下这个图，确认下，如果还大的话，我们就调整下
![WXWorkCapture_167723352664](https://user-images.githubusercontent.com/38368335/221153217-fb44a261-2548-4c94-83cc-ed880a42edd5.png)
